### PR TITLE
newtypes

### LINKED ISSUE #2: Add newtypes for strings used in OIDCCryptUtils
To increase type safety and make the types better documentation.

### PR DESCRIPTION
**Pull request by cryogenian**
fixes #2 
@beckyconning please review. 

Btw, why `verifyIdToken` is `Eff`ectful? Is it calling servers or something? What does `RSASIGNTIME` mean?

### CODE REVIEW

**Comment by beckyconning** [comment]
It verifies the expiry time of the token against the current time. We can provide an time in place of it getting one by itself but that would be extra work for no extra functionality.

RSASIGNTIME means RSA Sign: Time. I agree that the ALLCAPS convention is very confusing but I was just towing the line.

**Comment by cryogenian** [comment]
Ah! Thanks for explanation :)

**Comment by beckyconning** [comment]
This is great thanks so much @cryogenian!

**Comment by beckyconning** [comment]
:+1: For merge.

**Pull request merged**
